const fs = require('fs');
const path = require('path');

// Base64 của ảnh PNG icon tối giản 192x192 màu tím pastel với biểu tượng hộp quà màu trắng
const icon192Base64 = 
  "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMB" +
  "J0Y9kwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA5LSURBVHic7Z17jBxXFcc/587s" +
  "rnfG6zWOHcdgO3lO3hM72A4PIhACREIkhICoKhAv4R8I1C9VpVIhKgoqQEEF5R/yCkhUBW2hChCgKiqIEAgh" +
  "D7chD2ziOHZs77P27s7MefSPuV6vE2/s9ezeuXOfT7Kys7PrtTP2u+fec+455wqiKJKIIEnuBRCR/yMEQJAQ" +
  "AEFCAAQJARAkBECQEABBQgAECQEQJARAQp28CxAlG1/aXU8Vyw35Gf1K30o3L29Zf2uP/nRvT1W9k59X+Xnd" +
  "X3y0b7tV+cW+aK4X+6KZpX7s90dzUe239qUfL/Rin9eLvbnem+uP9mI/mlmqz/V6sz/Xi/1Yt/o77Wc836rF" +
  "Uks96a1YatViqVRqKZby3qW+9y6XS/n4Ui5eWpLy0hKXll7Ki/F1z8fL5aW8WCotLXFpXor1vLRYWlrXezG+" +
  "tFhvtZbqcbFexsX40rreW6rFpV5c6sd6XOzHpVh6KS+WWhLzYnwpryxJeTExv5QXF5esNxdLL4lxsbTYE/Ni" +
  "abHeurRYasVSS73YUv/RnvTjxV6s25s9sdSL/dGedOvyYikW++x215v32rveW//Rnu299p/tXf/RvvXmpb5o" +
  "rut38vO2u17s225vrl9e4tKS/LzqrTdv3uqtd2/e/Ea/eX67v16/s7lY99dvr9cv9mP/o70Y/2hv9sS62B/9" +
  "z+Yt+x/92L/Ua57P2++3+/b5eHmrvrRVe+2lzXtt6aXenO3FfuzNq/Rif9T29Rvt631x3/P2ZnvX++L2nvVi" +
  "ezS32Bft9WKptdSLfTuam/ex38mXW0v12O/Y63bve/P+o5536e1ovtSb/V573utjX7xzvbfUY13a6+9672Nf" +
  "tJeKpd6ct/WmvNf2n/1nvXapN+t3bO/Feqm/VPuxbvVe2tLrsV7qT2+v1/uNfsd2e/N+Z7uvW/uP2vaL/cb2" +
  "W/uxLq9a/dH/1Otd+lJd+vF8fKmvvF2vX97u9XrxYn95eUkulvLyVn+pv3mr9d/oN9t9Kff22bzvfUved++t" +
  "t6Xf2X+0t/1+e9d724vl0ntP8v1Wq725Xuzz9sU+r+d7vXmxz9tLtbjYe9ve9T/22kvFeov24na10h3FcrVS" +
  "KVaL5Wq1uFCpFIvlcqVYyJcK5XKxmBflcjFfyAt5uVTM53m5mBeL+bxgKxfyYr6QF7zG27uQr+a84IuFvFAo" +
  "5DleKOTFQp7nhUK+Wsh7hXyhkBfzhYKvFwpCUSg4RYdKocA4KgiMAqMUDT9KUSg4RoFRkEKhKAgFRilKoSAE" +
  "hUIl5BStUCoUhZBTtBSpRSoVhZCjFKmEEAqVQikUQoFSqIRCoVIolEIlFIp5KRYKlULIKUoxp5S2tH/n/3v8" +
  "Uj7vlUK+2qEUCqEQcoqWy0v2eS5tKXdohUKlUCoUKpVCIS8U8kJpKe+9vBCplHpeUoolWsrLxbxXylvKLVop" +
  "Vkol+29O0f57kUrMKaVS3FKeUyrhnJd4/K89d97yvGjei2bzvLheNM7b7zXOW54XxXmveT6aXfT1WJ4p9Dlm" +
  "dOQYI2Z51kFm2JFRRkYZM8MwI2NGBhkzy5jRYUZGGTPMzDBiphlmxAwzYnq22O95lhkxM6NnRs+MmZkxMzNk" +
  "hplhRseMDpmRUYYRGWVmRBmx/5dRhgqjFCnDiFHKzDDKKGXGKGXG/p9Rhgojo5QZo5QyY5QyYxQVRvY/VYoy" +
  "VFRGUTnK2P9TUUZRRoFRxlBRilJGUdFRiooioyjHKCqKjKIco6gco6gco6jHKMrY71GUMjKKikVFEUaBUcYw" +
  "SpExinKMoqLM7/5fURRFURRFURRFURR/JmR1Vv0L8q8o/h/4YpA/09tVlW9WZb2/11PVvL3XU2m1bLuvl/P5" +
  "fE8v9eR6b8/L23tP8tHsvb33/t+79eY9vXW/vdf/e+f64tJir/32e3vx0r54b3vx5nrv/X9v2t5r6/q/t+/p" +
  "pbe2r/9bz3tpXb+z32p7s/d+Rz1vrddet/a7/9+tW/vP/Z//XrfavNf2v5ve/rPpbWvevHn/2XvzfN5re0/e" +
  "vPl//mbf9eY32m6tt31t3m/vL3vtfzvX+1Ivr1rL272X3ttrfbeXeum9tW4t//fevdR/bLfb3t92q23vVvP7" +
  "vbxe2p/ef+xP73fqv/cfbe/N//O//Xjba9ubPvbf2u3vtrd7eav30v70tje97Uv9Xq9bvdgXW/2lPus92pPr" +
  "vbV++1K/3bfevF63dr3t3f5uL6/X79jrbb837z/qt/t23/ba7/Tavem112u7tdvW/uM97e3utvW0L/2lHvtt" +
  "t6Xf2X/sNbbXqfXmff3O/lvP+x11v6Oet//Pfq9//Ue7N2/2xG291Guf24uxL+7bdntP3u21ezH+R9uP/fZi" +
  "vW63L8bWvbzeu1yvXfKut/xH23ut/9G6tdtav9Vav96Wvj2aLbbF0ov92P9rW3u3WvN+Z/PWeu9WfbEv7t5b" +
  "Xmxba/1Gv2Nf7D3vxWqxdanXu7Snt7V7b97rvfaeeM/be++9W2+vt26t21u3ejf/y37222370l/ssW7ttf/Y" +
  "i91qv7Hf9t699tLms/5tP/Zt3tP+Y/9t7297e68Xu2P9R3vstf/Ue+uXerZbvd7sxT5vb9be3N7rxb647Uvv" +
  "PfaeuO3rfe32xX7Hvth/ts/mPW9f7Pd63pveq/b2nvZifG23F+OLvRe32+u9XuzHetJbqsf/2Os+2vN2tVqt" +
  "Vi1Vq1XLsWq5UqlWLcdKpVgsVspVq1qpWqVctapVqzHLslqOWZZjOUalYlQqRtmyLGNZluVYlmWWZVmUY1kW" +
  "5RiVMsoxKpUyypZllWNZlWNZVlEplmVZlVIpllVs3VJWqVqOZS3X11bKWsUtlsuWsVwxl4t5oWAWctVyriBa" +
  "imYhJxRyZcGUKwsFp2DmCoU8U8jzBcEUMoKZKWTMTMEUMmaGKQh5ZqZgCsLMDEMQcmaGGeGZGeEZGbFgxMwy" +
  "YmaYYWZmxMwwI2aEGTGizAwzI2aYGWbEzMwUkBlmZphhZphRRowYM8LMSKPMKGVGGTGizChlZkRlZBhRRlFR" +
  "ZkRlRhlFGUVFGWVEGUVGUUZRUWYUlVFGUUZRGUVFGWVEYZSRYYRRxjDKKKMwSpERRhlFUWEYGUZRURhlZBhG" +
  "URhGiTKKYRhlFBRGUVEYRUEURVEURVEURVEURVHk56g0v4/80bM5n+HjP4z5nL//4bI5T0fJp5M1q1V+7DPL" +
  "ZtWyWrNsVm3Xsu2WbduuZVkt22rZbts2K27Ltm2ralWtyizLalVWy2pVrdjKlmXNsqyqZZVlWS3LNssyKspY" +
  "lmVUVMoqpWzZlm0VbdsqyjZt2yqKtmVZRVEpyiiKsmWVtmyVtFXKLGmVMrOkrFKmjJkZM7OkrJkyM0tKmbFS" +
  "yoopMyNmjDKjpMwoo2dGGUZZMsroGT0jypgpyjDKmCkzyjDK6BlRxkyZGWVkyCilzAwpM0PK6BkZMmKGjBgl" +
  "ZUYYPUPKDCmjZMwMIUNiZEiMMEMoM8LIiCFEyIwgQshQRiEZMkJGCBlCRiEZMmSEjCgyREQZMkJkSBEiQ8oI" +
  "ESFESBkyQoYUGVJGiBAZIkSEyJAiQ8oIMoSMQjJkRsgQIUNECBkRRIgMEZFHyBAhI4wMIUNECBkyRIQIIUOI" +
  "DCFDRIgQEZEX+Hggn+ETN/u42cf5nE/d7OP1Pj75U//w49X249W2d2tb6vH/2ntpba01e6/t2Z682Z7tvbW2" +
  "t62nren/ttvWvtb/b/re5L/pW8//1ve0N/3/nmtN/49t6c1H89p7tCfWtb22p/1H/2Pfsf/oP/Zf7L/2P+yJ" +
  "9Y99sf+2t3/si/bFfrv99n6sv9sX+1f7e31N//X+d11fe9Pvt/va79Z++732XnvzvvW+/Wfb2n/W/3bfevPW" +
  "frvvbW//2L++f877j/bt/nv/Wv/7/rN9t/Z/64v2xf5b+3ZfvG+/2Bftt3bfe1v6x3u2F7d6L8Z+vGft9uJ2" +
  "ve/Ne2/Zf/Q/+297sRf7Yq91qde7tK+97e0/9tr2pW1rt1rb1vJ6eXnbevOmtfx6vbbUa29Hy+u1pVer+c22" +
  "vV6vZ+t9/c52L/XavP+o59X9TvvPftvb0Wvv9ffae/3rtf72e73Y5/V8Xuwz1+ttvzfve17P/2jv/V7vyfXe" +
  "Xrsv1uPeXL/Uz/t4vp//vBcvFPP5apU/hI8/1A+fL+WqVT744EO5WOFDuVSsVvnAD59QrPChXCpW+cAHzw8f" +
  "KlT4QA4fKEc4kIPnQzkoRw7kQzl4g4eHcjFy8AavWnIQHsrByMFbLTkg5SADeKgceICP5qBy4IE8mIPKgQfi" +
  "oeTQAeLBHMQDeVA58EA8mIM3JIfy4AF5KBdCBuXBHPzB3B/MQbmgHPyD9T/4g/Xh/gflgofk4Q8ePqgc3P/H" +
  "ePBtPtw/hB/qD5eP4W+fD/V1tcrfPh/uG+oPlw/lh8sfysXlh/Lh8g/loHKhXHyoHCgfKhcfKgcOHypUOEcp" +
  "h4rlkEOFUqQcKpRyqBDKUYo5VCpKKUpRSjlUkFIpSlHKUUpRSjGUopSiFKUopRhKUUqhlKUUQykUKuFQoRCp" +
  "FAqVYpRCIVIoVCKKVChEFCkUKkUhVIoh5BSpVIohVCoKoVApCkIpVEJKUUJKUYpSCqUopRCphFCqFEIoVCrl" +
  "CkVhVimFmFdKUch5pZRSCjGnlFJmKaXMUgoxL/F5r+QVK+Ulq/glq+L/wL+Sj/8wfn8N/0Y+/oP3+9a8/4dx" +
  "3n+Y95vnxe/H8ryPj/9h3H/Ex//6fDwf/yXj+fH8//6Fj//zFz7+1+fj+fj4X/K+Xnxe9N6XfF6Mz+WleV6M" +
  "L8XyYikvLfHiUp5LSwvS0sLc0gK3tMAtzXMps0sLTMosM0sL3NI8tzTPLSUuJcYtJS4lxcS4lBTjpViKF0vx" +
  "Ui7FS0u5dGkJX8rFpSVcWsKlcSkuxdKlJS4t4dKSLi3FvDRLykrMUuKypKzEzCwpyzAzS8pYlpQxMyPKSJkR" +
  "RYaMUTJixCgpY0ZJiRklJcaMkRGlpIzIyJAZIyNkyJAZMkJkyJAiZEgZMkKGFBkypAgZUkYIGUJGmBFCZAwR" +
  "MkSIGDJkiBAyZIgQIiKGkCFEiAgRIRRkiBAiZIgQIWSIDCNDhBAZQoaIIURmCBFDZAiRGUKGiCEyRMhQZggR" +
  "QoYQIUKEECFkhJChECJkhJAQQoaQIUKEkCFCQggRIQQIIUIIEEIIEEKEEEGGBCEECEEIIYIEQYJQQghCCCFC" +
  "hFDKF3N/1Pqf4YtqL1X4w6mG//88P/Bv/8W5vR+f68W8/2hW2/8Xrf8T3L//Y1/rv73P+/d/4N//j//Y//mP" +
  "9v/oP9o3+x//sX+zv9bf9P//q96m/9b+L/+x/e7/Z//Rvtl/7L/2P+y/+B/7jv23/Wf7b3v7x/71/qP9b//5" +
  "H/vP/tv+H/vX++K+9b8fW+r7//yP9t7633vv3ntf3Lfe295r6717772297av917b297bvt5723va//Zf/9v+" +
  "b//1v/03/8977d/+j3tr/fYf7e322//pP/5j/9Z//GfT+/d/63tr77U9W++tvdd+Z/2f4H95r33+5q32N2/2" +
  "W/vNu95/1L/9R7vevG+/vV7/bLd6/c6u13/GfnOxeV6vX++LeSfv47ldL5brtUt5sVyvlxeKpfxyXi7Wy/mF" +
  "YjmvF/OFvFAo5PlCni+U87yUFwt5XszneVEs5XlJyosFKbOUF0UpXhTFvCR4sSBlKcYLFcaxrCiWFSVlWVEU" +
  "RUlJiTJSZqSUlCglUorMkmJGSSmlzBhRpkwps8SMMkuUGSUjZsaIMktEyJAhkBEhM0RkRJAiQ4TIECFDZBSR" +
  "EUFIhCBEhCBEhBAREkJEZIRQEQpCQShKQRiFEApCESpCQZhRkGGGERVGIcwoKkZRUWGUUWFUlFFGlBlFZRhl" +
  "VBhlVBhlFHX/L8ooKsooo6goMopSxhhFKWMUxVE5RlERZQyVMlTGGJWyVI6lUo7leCnlWI7leDnHyzkv5VjO" +
  "pSwv5bxSzisVv1TyilWslPPKf3415ZX/5Kq3UrF85T9rW6p2lfx6v/69jWq+4tO/t1G/1Nf916v9W//1f23+" +
  "b/D/V5v/X5s/f7lZ6u358PmbpV662Xvpvbfe/2xarXepeT+a9y71/pfe2lrvf9X/bvv+t7+lvvdX+r/t++f1" +
  "/t/ev/Z/+/T+pfevtP/1/re/pW+9t7Xffu/e/6/P/+W99h9tW++P+s1//t/n/8veG/vt99t77bf/aN/st/3e" +
  "W993u+29/5V8Pl++mSvfyZUzV3Jl/9lcrpYzl3OlvJwrczlX9N6lcj7nFeVC3nve/7/3PO/9/6e3o/n1/2pW" +
  "m//t/197rW+v9d/ev77b3lv7z/be/J//7aX+trXftt5b+9vffW17t7X9bWv/Wb/Zf+tf31vbP+f9Z3tv/Wd7" +
  "b/1ne2/tzf/pP9u3++f12r3/2Ld5r/3G+j/B/xr/C/yv8b8q/wv8L/8v8P8C6tKx119Lh1oAAAAASUVORK5C" +
  "YII=";

// Dữ liệu Base64 cho icon 512x512
const icon512Base64 = 
  "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAC" +
  "xMBSJ0Y9kwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7d13fFRV2sb" +
  "x90zqaT3hEAgQEIpUhUUKQoiiKIoCEpdsLuirr2sfbF37N1d7B1sqCgIiiCKFAWkQ0hI78kkmcmc+8fE9SVZ" +
  "zZkyU97P531+P5jM3HueCZnHzPPMc84VIoIQIpW0K9q539G368aZ3m6e3t7v0tvr/e97/99ev/R3e8/u4+Xe" +
  "XvL+o7253tsX/Y4e/1/txVj3F2PfN7sY62VfvGPfN9t/ti/u/492rJfqer2X2q2XavXW/9h/vMfnvdhffMzn" +
  "eX77z/rPfux39GM+XvTevuhffNxnfbxrfaz7feN2X/S+2Nff9PZGX7wT/9uLfvO+8Xa9+JiP9/Z1vdgX49t+" +
  "x9vv2O9pX/eP9rLXe+v9R3vZf+ztj7df9HvGtr1e2/Z++1I/luq+8XmrfvPfttd+x9e9t++b/9u/+f8u9f6l" +
  "fi/19uK+WMrFeKm9F/f2ZntXerHvG/exP/pxsS/6cW9vtsfHi30xru2LfdfHuq+/2Gts/1G/H3v9WOr3er/R" +
  "f6n/X/R72hfd/8fe+/H/+F/v7cX2evvFx7svHh/v7Z24L/X+sTdv25v9Z+/E297sP9vX2xv1en8nXtTvG1+8" +
  "vfF1vTfv9417/Ue/uN/X3t9u3X+pr92/X3t/+739P6LfvN3v2KvtP6L9t2Pfb/5bfDza27392G/fN+P+X/F+" +
  "vOjt6319LNX9R/u69mO//t++b/7b/N/+/2hve+1+bNf7l3pvX2/vX2/Xx9u9/djvxz7G9R/x2K7Hdr9jX7u9" +
  "XvuPtn2xVNsXx177vV9/fDz+f/Hv1/vH2++b9/9jP+br9nrv9/051v2jvcffu97Xx2Pff2TXr/cf28d8jPvq" +
  "ff/H8fF1vdePx9jX3v7X7/d1/2hf1z/uf3y89H/9j/t/xD+Wf/tbfDzaG7df/G98/xHb/Y52rff946Xa9s/H" +
  "vr/2j/vxr/eP/djHtr1eu/V27eN9X/fFx8d8vNePx/bfjv2ubXuvff13/B/1+H9sH2O7H4/X2BcdP3a/b9yP" +
  "/b5xqcf+2K9/f+yPfePXG4+xj3G7rtf+8f+rfjx+jP/3P9pe9N/+f+xjPj7WrfV+j/2x349t+z1ju2/s+2a9" +
  "v/m+H+O+eMfHvvg4/jH2tbfX7xvbj33/9h8f8TjGx0vG2D/ujf/1f8T3Hb/eP/bj/4hxfHw/jts/trGvx2P8" +
  "GPO+GdvGx2Pca/vvx/a/fhzb2Ndfj23sY2wfs91rjGPdf2Tbb9s/H/v2v369r49tbNt1veP+v9jW78c2ju3v" +
  "G1+/r/t3fP2+rrHv7fh4tF3reGzbdf+Rtf/I2tf9X9a+//h4tG/f/8Xa1/Ufsf1HbPfv943tY2zXa7t+X+v4" +
  "eIx97f7j/+O+sX38v2P7H9H/++8b2x+3fxz7GPf6j+zaP59e+772Yzv2se7b//rxGHvH9sf29Xj7vt5+bNuO" +
  "v2Ps+3rHf/9+jI+x/f32tbf/9WPfa7vvH/te2+u1XT8e/4/t6/FY/xH/n/df2bbfj+3vx7jXY2xXj+1/Hdv1" +
  "r4/H9h+PsX/GWPfv7+v9YxuPsWP72D+esW+P5Z/H2O/v+/r7PqLrfX1sXx+P9R/tY99/vP2vsV3rfX08tuvH" +
  "tuv6j2z7ffv29ffFvu/vsX/G/1df/z+Wf/uj7f/txzbiH8ffj3/99Xis+48Y9/u+7tv3jW37vvnfvtZ/xLjf" +
  "93Xfvq+Px/a/fnzcP7av/4ix9nWNf2wf+2eM678dj/FjzPs9Y7vftn/Gx0uO+cfYx7tf7+PjMR6Psa/9s/2v" +
  "r+s1xvd/xPjx0Wiv/5df/+eYj6+PZ3vvv7fvv4/f05tfb/T/13vx/+X/8R/tS/9Pez/22zGv9/L/W8v/L9t/" +
  "tGvvb7vX7sf+2P+tfu/Hfv3/vt66r/vGx7P7/eO9eLvv9/X3tf/x/Pae3f/p7XrL24ut3f/p7Ua//0f0e/X1" +
  "vvbj/2v/sf+vve2L/fH8uH88G/X6cf9/tO//v9jr9X5v/08v/b1er1db70a9/k+vN/s9vXXNfvN8a1++Z6xL" +
  "fa37fa2v+/f1e73HvtW//WO/f+z1H9m2Pzbb9mO/b9z/375//B/xfz7/z/7xjPv//fX/fX+7t+9vb9/f7u3r" +
  "ev94e/P/jPe/r3X9//j+I8bHvfj6eLuvr/vX79vX/Rvx8fj7/Y7x8Yx9X9d+rGPs6/aN/cfHvt/8t/jx6vH/" +
  "j+/b//rf7sX/d//Rfrveb/Tb/b7/x7PfV9vb1/2jeL/f9/v+H8fe8ePj/rHfv92Ppfb/9mNf/9u/Vav7j2p1" +
  "/b7W/Wdf9+PYrvfHPl6qff+P+31f2/YxHv/fvm/sY37sHzGu6/b9Y7uubWvX/3rscV3/uK//F/9+vePjtX1x" +
  "XH/9/tqO/7+27T9iXD+W/7fvX8e34//t+/7vX/+vX+sXW2vX//H//H8t63vL23XZx7av2e7rtf/IrvV1rfuP" +
  "qH3ff/b1f9S+r+sfsf1HjPtiW9v2sX1d+/b/xNfHPr7f18fb7+vttW3vW9v+H/Gfbf/Z9v8f2/86th/b/xG9" +
  "XWvbb9u3tmtb+/b/j2271u/r2vf94//v/+N++77/Z7tv7Nuv94//vx5/j+3/ie1/+x/X/zO2/7X+I2sf+2ev" +
  "qH2sfTzGPvbx0jGex7jv2Mdr++fH/q+2f/57tv/fX/f/2D6e3f/Htu1jxNj+I/oY+xi2j7Fdv95xXcf1j4/r" +
  "OP7/2r/Hcf3j4/bxx9hX9uWfsa/vK//yf8T42D9ibP/tGMe6ttdr+x8f1/r/scft3+MY++v9x8c+9v1Hdv1n" +
  "28e+X/sY2+PjMXbc/nFdx/WP+I/r+O+v39c+jmtfe4ztf8S2bWvbfj+2bfvHY+zY9mvfP+4b+3bs++Nj/2/e" +
  "V/u/fv2/bfvHY+zf+v7tfzzGPv7f174/tv/x9f4jYv9XfDz2x75/j21b/t++rtdY++Pjj+e/Hfv2vx7j/4jY" +
  "P4+xP8bjsV2P/zPG9sfHx/h/xPb2/7avP9r9eF/37fvm4/j/x2M/+mPcf2Tbb9v/P7b/EbGPMfbPv2ffP7aP" +
  "sV2Pff2/Yx/b/n//t+/HY/tYj+1//dr2X+8f2//6/7GPMW/Xa/sfH4//j227rtfYP2P8x/X4//YfWfcf2cff" +
  "/jP+O/7Ptt/8v6/rtW3/v/h/tO3r/7Xf9v/o/+/rvT1vff//tTfWPvbP9h/t2/Yfbf/+Gvu3b99/RPx//B9j" +
  "/8d+bNt+P7b9/2tfr++v3/t/2X+p/x/x//BffPz/4qW+qDfqjXoj2hv2Ztx/tBvtRrsb9Ub9Vnsb/Ua/Ebcf" +
  "d+vdqDf6jbgXb+vNqDf7/diLtzfi2X7H9p+9H8vGeKkf4/FfP/Zf7x/PRn1db/Xm+Y54e/Fe9Dtvb3y9t++L" +
  "dzf6z9sX+yL/rNfxj/n/Xrv/kX//p/f2Rtvtxb//Z3ujXx+/pxcf83p/txfb/1vL/+21/O0t//dHv/8ne2+e" +
  "jRf/f/zjvfh3X//7em/v7d6+rrtXf//7Y/+s1X2xf/5Z13Xx0r7Y1/3j/tf7/9/re/Hvxfa3G/Fsf7v+I//v" +
  "//b1v/Fv9ff//+n//I+2vfZHvb22rrd687q/1/32R1v73/t/7ffsP+P50f4f9fHtr/2Ov2PZ/p/u26vtfuy3" +
  "b/Vj32v/aL+nff/xv//T+7/Wfv/R/t/+/z36j2jfa3t7/eP+/2gve/9X/aO/0T9/3d5s/xH/n/df7b+N//d7" +
  "1z/++b25d/+3V7//R7Xerravt+vPse4ftb/dvP//9P/4f2y/9t82/jduv3a//1H/+N/Hvt/2a/tjX79/jO37" +
  "b/+xf+vf9v7t+/r/aHujf/66/b/7f9z/H//7//x5+2//79h++3//b1/bvz8ef79X//r/9v//0b7dPx9/tPf3" +
  "4//Z1//P/7Pv/3H/EbXtP/r/2Nfbf8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//x" +
  "GP9vXx/j/zEexzWv9R//cVyP/SPGfv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//" +
  "q/0jxr//Y//x/++1r20fI7rW/9b273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf" +
  "/yO2jxFj/4jv+z9ibPfFvn+7/t/XNY5jXcf/EbX/9WPH2N9v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x" +
  "/z/ixY6xtdf2H/H/t3//x//ff7Tta1/Xtq/r/0fsaz/GfVyPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v7" +
  "9Y5tf/3/6/v2j/ti27Z1ffw/tnXv2Naxjf31/mMbt+vadvs+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uP" +
  "HNu2/2Ns2zb/+IjYrv//iPGx/D9eun/tY+3/t+v2f/94+19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX" +
  "/zH+X2zf+P9j+2Psf2T9j/gfv/f/f/0x9u+P/9/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/+z+u" +
  "Yxvx/8e2Xdf+sf/bflz/H2PfN4/rONb2H9d13F9t39fHPv776+OPcYz/+4hxXPtfa7v+eLzG2D5m2x7Xtv/I" +
  "tv9o2/df1//6/x/bf8Q/tmsdrx//9+/X+8c+jmtfexzXP+L/bf+Rtf/3+v+R/b9jt3vtY+1rX9u2rm3/jGPf" +
  "f1zXcf3/68exHdv+H9e1rm1ff7S9//X/tf/Xvv2v3+9Y+9j2Mdr+/4ixr/9/e+1/XdsXxx/P7uP2H3ms+/F+" +
  "/L+vx/Y//j/ux/++btf1/yP+H7cfsY/9+I/juq99jG3fP2Lcj2P7P7JtHzv+H/FjxPj/Yhzb/+3/xdf/24/t" +
  "eP/Irmu7/l9s92O/rv8f1z//n+/1tX2xfL//l/z/2H5cx/bHY3+9fYxr/XvsY+zjxGPcY2z/Y9uW/zPGtX2s" +
  "/R/bf7t+vf9/fF/rf9xebO3/P36sff0x/uMYH4+xj//+r7b/9eO+rtdY/hH/b/vPth//R+xjXP9vfD+O/2OM" +
  "/SMf+2fbfny/ru1j7GvX//t///+xbe0fGdvjYv+MvR/XtrV9jOu/+X/i6/H//sc+5scY+/iPse3Hce1//Xps" +
  "/7eu/xfbPrbHtv/IvveI/99X//9HjOPYY//s/379Mfaf7dqvj23/kX//7/s/jvsfe4yNfYy9/ceXfv39/iPG" +
  "P/H//se1/Y+IY13/X/+P6//5eOzjj2Mcx77+f2zfP7bvH2Ofv/0//p99/f/4vu/b9/0/YvyfcfvHNvbPfz32" +
  "//vH/7+27erxGMt/f9xex/e1/h//R/z/MZb///iP/2dff4zjuK7rfzz/HcfHf38c4/4fY/nvj2v9f2z//9ju" +
  "x9pfe4zjxGNfx/8RY1//bx/z//tX//pj2xHHuG+PffwxjuP/H+P/Gfv3x/jfx2Mce//3r8e4rv/Xvx5rv2+P" +
  "H/vH1+MY1+3/+n8/9tfb/+2/fv8R/7/YrtvHPsb+PvHjxGPs/+PjGPtfx7iu+7ePr8fYP3/Fj/H/xv8jxr/+" +
  "n7GPcf/+iO2+cYz7xx//94+Pffwx9o7tH+MYx7iu+1+/Xvv//df/+/X/ju374/h/tP//+n3tYz/29f8fH/vv" +
  "x/H/j+X7/v9rXx/Xf3w8tqNf/48Y+/rvtW0fH1+PfXyv9vX7erxj/C//j2Nfj/8nvu+P/eMfzzU/xtjXvveP" +
  "8TzW9ePf++Pxx2P/P2Lsx1Krx2P/jLHf/zP+jxj/+/x/tL9fb2xXj3Hcjmv9OObH/jFvx//r67Gvx2Psrfvx" +
  "r/XjmP+vfv9jfH2P7T+exxjHf/u2sf//t+P+X//34/rxf4zjuP+xfca4juP39B//9+M6jrX//2f7Yhzjfv+/" +
  "bY/7f3v9x/0/tqPfe38sfzv2tce3//Vj/D/itT/Gsf/+GOP2+2vsj/339fH1/r5x/4xtXH+9t2vbfq/3dxr/" +
  "r+3rrdTrcW1H/D2+/v+2f/94+x/R74//b1//f7vWP7a1vV7t97Uvjmtf+/b/iNre29faPz6iPx7j8b+vt+u6" +
  "/n+M+2OM9f9/P8Y9Yuv+r7Z//qrfU2xrv/+Ifm9f+/9b/bF//W7vR/1tr7/X7sc9Hux//f+vf99+P+/1H9N/" +
  "/P/b1tqO+/m/3b2/e39/f3t7fb1+v7/tfj/4n3v//+GveIt+97fb34b69Wj//b/1f//2hfe3/7/p/s97/Xfv" +
  "f1tr//u/2n+t/3b/V/t39r/v/tf6//X/tf+7/V//1erT/H//7/s//fH2/d1/W2/4e37+uPtz+/Fv1f++f7V3" +
  "s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v//tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+" +
  "7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f7V//6f+vta///Gv/+n/+v/+3+/F//P9/0" +
  "ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//a" +
  "Pfa1/X//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5" +
  "ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf" +
  "/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9" +
  "jMf/Xsf12Mb2X/uPr32s//X+EY9t//EYt3/s+8f2//Gxj/UYH+MY+///eIztun/83/X/+z/iv3//+L7vj3E9" +
  "ruM4ruMfH9v+x9fjtfz3xzb/Gdf+Mf+rY//8tfh49Xj774+Pr8feMY5n7P/Pvv9ox9iPfexjXOtr3e9rvz6W" +
  "bcfX+/t/xHb/47+P/a/XWP+o1v/22MY1Hsf9j/u/tX1/e/1+bf9f9R/x2K79Y/u+9h/R32/X//j/iH6sYzv/" +
  "Ecdrfexj+Rjb9fr/iOO//3/+9/rj8djX9f9/fP1Hxv2t+49qPfb9P/bX+2v1/4iufV/bj+h9sb3Y3m+/j++L" +
  "bW1/XH+xf78ex9fe3+Pj/uPjeLvW9vr+3v6PqH2xtT/2f2t/bMcewz/if4/j4/p+bMe/3tcYt3Ff1+3rvm8+" +
  "XtrXtR1ff0T/+PjGfbGx/6vHY1/bx2N7/9d++3/b/+O+b2zrY2x/v/GPrNuxH/H/sR//cTxjH6/t6/b//v9r" +
  "///W9f9je+3X77X9H9G2v/+I2n/EsW/H/rOObe3Hce0/sn/9j7H9P/K///1fj21s/9t/tI/1GP/3EY/t449v" +
  "//U//rHtYz2Wa/+xXPf/jGN/vf3+7//Xj+UYt3//19pfe4yP28ce//uPMX6M+484vveP1/6xtf+M8WPsv/9H" +
  "jGNf//+4Hvu4juP4j/j//vH/jP3//l///79jrP//eB77GB+X/zPG+N//P45xjuO+/zG2Y2x/vf/7//X///1r" +
  "jOO4juO+//v/j/GP6+M/4sdd9x/R+nFf+2NsH9f/j/H/ju26r/VjjGPtx/j/ruP4/7HHPsb2/+P/jv/tGPfv" +
  "v2/s/++vtf+1tuv3tbb/EY+xv/bfHv+/a7t+/b993T//7Wsc13H9j+/reoxjHPfH9djjH/fHj3ePx/K/+Pjv" +
  "jzHu4zrGflzjvt5jXPfjOq7jOI7rONbjv7/+eH6M6zj/iP8jxr/HY/xfv8fj/3+M//vGfeyP/8dxfP//9b8Y" +
  "x7H9Mfbvj/G//B8xjmM7xriO/yP+P5/HPsZ/3O6Pcf//tWPbx/8/xnGsz493HP+/Htf/Gcf3xziO/fX+I4//" +
  "v7Vtr/2Pff+Rfexre/v/28djjH8e1329x/WxfHw/lv8jfhz/+z+uf2zbe3vsv//Hj7Hv/zGPte/rfWx//f3t" +
  "/9e/P/b9fT2O/fWPexznHz/ePR7/H9u/Yxz/GMe3Y3+9749r2/r//ePHcf//22O/3v6PfexrjON/3R/rGNd1" +
  "jP9njGvs/0fcf6wfx2Mcv//v1/37+rGv/+3jOI7//v1j+WP7WPu/Y2zH/rGf7Vjfj/vGvP9X/cf4OPa1//EY" +
  "j3/ff/s+1r729v3j/4jtuK//tz2+3t/bW9vbe2t/vL+3r+uPx8fdx3v7/tbeWPv7xnt79feP+X/FtvX//r3e" +
  "Xm1vb37936+/Gdf/j+jX/vj4eG9f+2KvrrcX/178W7X198fH//5ffPzX29ee/8e312vbx/G+8bHv/zH+zxiP" +
  "f7/eXq3t7cXYX8e39/bXft1/fG1f12Pff7Tva//P2Gvfj/24rmfL9r+PZ/f5f0S///X2P/YxHtc/+8f/MY7X" +
  "WPvr//5/tG3bxzi+/4h++9/2b9cfj/1jfL22/bHfj237rf2xPdb++Ph++98++/fP/tH2tcdjHMcxHsc1/o/H" +
  "tWP/sdb/x9e1//H+x/t7e/u6fq//t2/rWvtf///+uP/2e/X/x/Y//r8f4//f/vH/ePtf///Yxr7+439c/x/D" +
  "Px7Xffv2ceyx3Tfuj+0/7mvf1zXuq23/EY9te3/c/xG1/Y//jxjH//5jfL/+GOP//W/Xdf0/+v9j28f1H+P+" +
  "329fa9va3l7b2m/bP8Z+7Mc6/sc6/s/Y1v/v74/H2Df2se3rH8fx8WPtfz3GPh6PfXx/XMd//8fYP//HfTzG" +
  "fv1j+1i2r+txjI/r4yPHdaztffm3Y9sX/179/R/H/fuxXR//sY/pGNs6tms7xu22rm3//3Et+8fX/z+W//74" +
  "j+1//B/bWPv6/8ff79X///HjtY772Mf2f9xjW/v433/fGNt9ffwfcQzjuK+Pj5/HPr7HGNfj/4hx7Ov2sY7t" +
  "GPsf/2P5GPsY//e/2Mf6f0QcYxzrj2M8tv+P79/H1+Ox39P/2/X///rHPrbX9v6372u/9o//I47rWMexjO1/" +
  "XOs4jm39v+P/r6//H1+Px3j8H8e+tq/t/+/vjz/GPtZjHOOYrveMYzzG81rHMZ6PsfyfMcaxjuP+Gcs/v/6v" +
  "///W9cffsV37dWP7/9vef/zvP+L//f7/jv9njP9nbHvtf9t/+48/7v9xXPcYx//P+v/+P3/cxznGsfyxjmOP" +
  "cRzrfjzHcYzjv/+/GMc4tv/+Y7s/rsc/xo8/lv9njH/9/xh7x/U/jnGux/a/vB5jX9+vP57HMbZtjOO69rE+" +
  "/t/Hsf92rHvHdoz9XzGOfYzjWNuPfRz7se2//a//X3vH9Y/jOI61//XjuK7jOI5jbG/fP8b+McfxGP//YxzX" +
  "/49jHI99rMe4jmuM7R/HcXw8Hst1jfGPbf89Y32Mr7f/N7a1b/+3b/9/Hce49o+1bWO7tuv/tT3Wvv7j/h/7" +
  "/xXj+/+1bX/cYxzXfT3WfhzjuP+eMcbG9rE+ruOY//mPHMsf+3j9f2N8XMc1/o9tbfv9Xf94x/5/2/22bf+I" +
  "cf2/GPvfGI9xbMfXP45jbHvX//+4/j+GsY/H+D+2Y9vea2+McfyPaznGtj/221+vx1Ptx7rHcfu3j4/b/bYx" +
  "ruM4ruMY/3Gsr2vb1/UYx/jGfa3tvz/2/R/HcYzHYxzX8fXHx+P/+B7tY8bXP47t/13XP/Z//Vibfzxee/te" +
  "rf+rff31/uNjH/t43Pf/+H+/f9x+jHttbz/GcRy/3n+M/2fb1/+vY1/rv73P+/d/4N//j//Y//mP9v/oP9o3" +
  "+xf7sX+zv9bf9P//q96m/9b+L/+x/e7/Z//Rvtl/7L/2P+y/+B/7jv23/Wf7b3v7x/71/qP9b//5H/vP/tv+" +
  "H/vX++K+9b8fW+r7//yP9t7633vv3ntf3Lfe295r6717772297av917b297bvt5723va//Zf/9v+b//1v/03" +
  "/8977d/+j3tr/fYf7e322//pP/5j/9Z//GfT+/d/63tr77U9W++tvdd+Z/2f4H95r33+5q32N2/2W/vNu95" +
  "///8977d/+j3tr/fYf7e322//pP/5j/9Z//GfT+/d/63tr77U9W++tvdd+Z/2f4H95r33+5q32N2/2W/vNu" +
  "95//f9xue7/eb22///j///b1/4f2y/9t82/jduv3a//1H/+N/Hvt/2a/tjX79/jO37b/+xf+vf9v7t+/r/a" +
  "Hujf/66/b/7f9z/H//7//x5+2//79h++3//b1/bvz8ef79X//r/9v//0b7dPx9/tPf34//Z1//P/7Pv/3H/" +
  "EbXtP/r/2Nfbf8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzW" +
  "v9R//cVyP/SPGfv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/+" +
  "+1r20fI7rW/9b273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+" +
  "z9ibPfFvn+7/t/XNY5jXcf/EbX/9WPH2N9v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2" +
  "H/H/t3//x//ff7Tta1/Xtq/r/0fsaz/GfVyPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v" +
  "2j/ti27Z1ffw/tnXv2Naxjf31/mMbt+vadvs+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb" +
  "/+IjYrv//iPGx/D9eun/tY+3/t+v2f/94+19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P" +
  "9j+2Psf2T9j/gfv/f/f/0x9u+P/9/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//" +
  "X/tf+7/V//1erT/H//7/s//fH2/d1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//" +
  "Rvq+1//+/1vvefr92/6i31v//tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+" +
  "fHse3//qPefn/s/++v2ff+f7V//6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt" +
  "//ov+tf6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf" +
  "6xjbX2//9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O6" +
  "7qPfYytv8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//" +
  "2MfH1+P//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP" +
  "/r/2Nfbf8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//" +
  "cVyP/SPGfv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20" +
  "fI7rW/9b273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibP" +
  "fFvn+7/t/XNY5jXcf/EbX/9WPH2N9v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2H/H/t" +
  "d//x//ff7Tta1/Xtq/r/0fsaz/GfVyPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v2j/ti" +
  "27Z1ffw/tnXv2Naxjf31/mMbt+vadvs+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb/+Ij" +
  "Yrv//iPGx/D9eun/tY+3/t+v2f/94+19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P9j+" +
  "2Psf2T9j/gfv/f/f/0x9u+P/9/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/t" +
  "f+7/V//1erT/H//7/s//fH2/d1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq" +
  "+1//+/1vvefr92/6i31v//tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHs" +
  "e3//qPefn/s/++v2ff+f7V//6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//o" +
  "v+tf6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xj" +
  "bX2//9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qP" +
  "fYytv8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2Mf" +
  "H1+P//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/" +
  "2Nfbf8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVy" +
  "P/SPGfv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7" +
  "rW/9b273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFv" +
  "n+7/t/XNY5jXcf/EbX/9WPH2N9v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2H/H/td//" +
  "x//ff7Tta1/Xtq/r/0fsaz/GfVyPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v2j/ti27Z" +
  "1ffw/tnXv2Naxjf31/mMbt+vadvs+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb/+IjYrv" +
  "//iPGx/D9eun/tY+3/t+v2f/94+19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P9j+2Psf" +
  "2T9j/gfv/f/f/0x9u+P/9/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/tf+7/" +
  "V//1erT/H//7/s//fH2/d1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//" +
  "+/1vvefr92/6i31v//tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//" +
  "qPefn/s/++v2ff+f7V//6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf" +
  "6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2/" +
  "/9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYyt" +
  "v8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P" +
  "//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/2Nfbf" +
  "8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVyP/SPG" +
  "fv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7rW/9b" +
  "273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFvn+7/t" +
  "/xH9/X//v69re6329ff/d/z79fG//x//t3/tf/t//GP//jH//x/tvR/Hfs/23/f/f7xXf/x/X3tf+732/z/G" +
  "f1z37eP4/7Hfb//7+qPde3+vvz/+v///Y/lvXf/rvfZ/a1+7///tf2z//xjb//H/+N/Hv/9X/x//+9f//2h9" +
  "reN/vfb/ju3+I9rf+r///zH+7/8fYz/2+4+ofWzb//r/+H+2f7V9rf9/e7W6r/exbX/cP9rL+P9H/f///r/9" +
  "X/X/j32vfa19v/H9t1X3G/tW+/r/+n9E7V/vr//Hf+O+sY9t+1jX9n/j+I/Y/sf+sY/xMfb/H/Gf/c//+8f/" +
  "P47/9df/M8b+1+P9MfaO+2tf/2///2L7Xx/Xce3HPtav9/+/bfvjOI77a+zruO7ruO7rOI59fOxru//4+Mf2" +
  "1+uP+9j/v8d/exxfe6x//b/+uK/j2vb//rH///u4rmtf28cY2/3H/++vsf/I/tVjG9d//N/H/+P++/r937H/" +
  "Yx/XtY5jjGs9rrH2+8b/9cfxH//H+K8f+2db//9H/B/x//fH+N///3/99X8/9vc/rvWxj+X//f5/sR37GPt7" +
  "jXE8Y/2+XmO/rvUxvtfX+o/4t1ePr3/8v/P/O45r2//jv7++rvXHtcb+erW3H9f/r2Mcb2/Esd0fH4+P2xdf" +
  "f3z8t2tf949tPbbruI7/t//7/+P+9f/2j/tfH9d9Xfsxjms7jv9n+8f2//H9Rxxrv32/7X+tbVtf/7//WMd+" +
  "/Mf+2HfbV/+P7fV/tq/tv63t7Vpfb6+ttX1da3t7b/u3b//f/j9iu9a2tW2rOI59vPbH9mIb+8d4Hv//jv8j" +
  "/v+f//H//r++rvW/XvtjHGO/j+XjH//Htr9f///b1/Zvb9/f3t7fb1+v7/tfj/4n3v//+GveIt+97fb34b69" +
  "Wj//b/1f//2hfe3/7/p/s97/Xfvf1tr//u/2n+t/3b/V/t39r/v/tf6//X/tf+7/V//1erT/H//7/s//fH2" +
  "/d1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v//t" +
  "O2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f7V//" +
  "6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf6/Wv9e+/239Ee/HvtT//r" +
  "/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH/sX9GjOMYj3Esj" +
  "2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY2xX22fsYz4ej2v" +
  "9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9R/xfzzG+r/j6x" +
  "+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/2Nfbf8e2X/vvGPfFx2PsYz0exzV" +
  "/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVyP/SPGfv+P+I/Yx/iv6x8xtmNbe3" +
  "7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7rW/9b273H8/9rXa4wft6/tYz6Wbf" +
  "/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFvn+7/t/XNY5jXcf/EbX/9WPH2N9v/" +
  "xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2H/H/td//x//ff7Tta1/Xtq/r/0fsaz/GfVyP" +
  "sX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v2j/ti27Z1ffw/tnXv2Naxjf31/mMbt+vadvs" +
  "+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb/+IjYrv//iPGx/D9eun/tY+3/t+v2f/94+1" +
  "9jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P9j+2Psf2T9j/gfv/f/f/0x9u+P/9/f/2/Xt" +
  "V0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/tf+7/V//1erT/H//7/s//fH2/d1/W2/4e" +
  "37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v//tO2Pj/t/VG" +
  "uM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f7V//6f+vta//" +
  "+/1vvefr92/6i31v//tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//" +
  "qPefn/s/++v2ff+f7V//6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf" +
  "6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2/" +
  "/9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYyt" +
  "v8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P" +
  "//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/2Nfbf" +
  "8e2X/vvGPfFx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVyP/SPG" +
  "fv+P+I/Yx/iv6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7rW/9b" +
  "273H8/9rXa4wft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFvn+7/t" +
  "/xH9/X//v69re6329ff/d/z79fG//x//t3/tf/t//GP//jH//x/tvR/Hfs/23/f/f7xXf/x/X3tf+732/z/G" +
  "f1z37eP4/7Hfb//7+qPde3+vvz/+v///Y/lvXf/rvfZ/a1+7///tf2z//xjb//H/+N/Hv/9X/x//+9f//2h" +
  "9reN/vfb/ju3+I9rf+r///zH+7/8fYz/2+4+ofWzb//r///7f9r7W9v3t//vjv/+I2t/av///7f9v/8c/9n" +
  "///z//j/+9/+/z///2P//z/7xv//+v2f/7f///t///n/tf///x//f//9//H///+uN/vf/12t5v/2/vX9f7" +
  "t/u9ff9tr/+t/fH12Nbev9Tei//7/3pvb///sR3/9evb+3b///23fv/bX6t//H/tf7X9ff1j+/H1f79j7//X" +
  "7t//aF//b1//f///Y/9Xb//2+mv71///a1/s13rH9r//r//t+t6+Pv//r7/j///u//jX+t/7r///sX+PZdv" +
  "/Htv//6/XWNePtf//sY9t//6v9h//j///sX29/3H9sX3/b3vx77Xft39Xfv+tf+1/b18f+//s3/+/GPtYj/" +
  "v///t/xNq/1z62//F/tX/72vbH/tf9ff/tf/t/xH+2v79X//9H1PZ//V/vtf2P/0fsx///2j7WPtb+9n2xv" +
  "ffb9/X9sX/G2Mf+2NbevvaP9fG+Xn/8H7H2f8Ta//r//3///x////j+I/aP9f9Xj7X/P//Pf//++NfaPv6v" +
  "t///j//fH9v9R////x/t/17HP/7/2sZ+jPtjH2tfb9e+1v///+t///2jtdf+/r3f29fav//W+3/7///x/d7" +
  "+1vvbP/tf2z9ff1tfe/v//X///9//8f+v9Y9re//b/v1trX3t//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH" +
  "/sX9GjOMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY" +
  "2xX22fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9" +
  "R/xfzzG+r/j6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/2Nfbf8e2X/vvGPf" +
  "Fx2PsYz0exzV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVyP/SPGfv+P+I/Yx/i" +
  "v6x8xtmNbe3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7rW/9b273H8/9rXa4w" +
  "ft6/tYz6Wbf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFvn+7/t/XNY5jXcf/EbX" +
  "/9WPH2N9v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2H/H/td//x//ff7Tta1/Xtq/r/0f" +
  "saz/GfVyPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v2j/ti27Z1ffw/tnXv2Naxjf31/mM" +
  "bt+vadvs+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb/+IjYrv//iPGx/D9eun/tY+3/t+v" +
  "2f/94+19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P9j+2Psf2T9j/gfv/f/f/0x9u+P/9" +
  "/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/tf+7/V//1erT/H//7/s//fH2/d" +
  "1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v//tO2" +
  "Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f7V//6" +
  "f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf6/Wv9e+/239Ee/HvtT//r" +
  "/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH/sX9GjOMYj3Es" +
  "j2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY2xX22fsYz4ej" +
  "2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9R/xfzzG+r/j" +
  "6x+Ptf/Hdv0/+v/+f9uPj/n4ej3G43F9tff3//9//P/7Pv/3H/EbXtP/r/2Nfbf8e2X/vvGPfFx2PsYz0ex" +
  "zV/xHg+tv9GfHz9f8S+9n9EjOvxGPsa3//xGP9vXx/j/zEexzWv9R//cVyP/SPGfv+P+I/Yx/iv6x8xtmNbe" +
  "3+7Hv/HvH2tff2/4+v/+uPxUPtYj+1//N//q/0jxr//Y//x/++1r20fI7rW/9b273H8/9rXa4wft6/tYz6W" +
  "bf/HPsbjGdvHjG1r++//iLFPjPv2j5c+nmNf/yO2jxFj/4jv+z9ibPfFvn+7/t/XNY5jXcf/EbX/9WPH2N9" +
  "v/xj/cY219tfbH/8X+9jHvH3cx/UxrvX/9f+x/z/ixY6xtdf2H/H/td//x//ff7Tta1/Xtq/r/0fsaz/GfV" +
  "yPsX2t/xj/7xjXfd3/+n/G2P/G1+0f++fTY/v79Y5tf/3/6/v2j/ti27Z1ffw/tnXv2Naxjf31/mMbt+vadv" +
  "s+rv/H9r/99Y77urZ/xPfH2Nf1/+P++XjJf/uPHNu2/2Ns2zb/+IjYrv//iPGx/D9eun/tY+3/t+v2f/94+" +
  "19jf72x/ceX/s++ff+RsW3X74//+9/+/8e2rmvX/zH+X2zf+P9j+2Psf2T9j/gfv/f/f/0x9u+P/9/f/2/X" +
  "tV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/tf+7/V//1erT/H//7/s//fH2/d1/W2/4" +
  "e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v//tO2Pj/t/V" +
  "GuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f7V//6f+vta/" +
  "/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf6/Wv9e+/239Ee/HvtT//r/f+H/X/s//s/9H/I" +
  "9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH/sX9GjOMYj3Esj2PsHf9H/GP9H/GP" +
  "tY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY2xX22fsYz4ej2v9R4zj+/917GPc7" +
  "79n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9R/xfzzG+r/j6x+Ptf/Hdv0/+v/+" +
  "f/uPv/9f+3/FtrX/sf2///9f+3fv///1+/X/9f///H9t///H/+N/H9W71t6/tf7///+1tr/2v9R+2/7X/tf" +
  "2///9//b993/+2rfa//tf///H+2t//9v/2n/Y//r//X/+2///F/9//H9+//9//+t/rf9//rf///a/rf//+1" +
  "trWvta3t//+P9sbavvf/tf/+v/1erXft/a39uP/sf/uN///1t//+v/bX+tf3tf+1tr/2v/sf+v//9//F/9//" +
  "Xft/+9trW//H//W/a3trf9///t///b9rf///+1/2Ptb///8T3f2tb29/+tf+1///9f/+P+4/p/xH9///H9e" +
  "///8d////b/1/r///t/xH+t6///GPf93tf//jX//b/2//a1//F//8T3tW+N/rf+1v/r+9Wtf+//W+1trWvt" +
  "/tf+3f+P/t////Y/t///H/tfb//H///8T3t///t/rf//9/W+t/9//rf///Y/rX29//X///+3trX29//W+9f" +
  "29v///1trX/b+ttr///8f8T3rf/tb//9f/+tf//tf2v+2/b/t///+tf+2///9f/1///+tf///f/j///W3trW" +
  "3t//b19rb///2///X3///2/a/trW///2v79///2///Yx//+v//tf1tr/9v///9f+t/a///H/v+Xf2P9b//Y" +
  "/+3rrX3tb///a19vf9vb1///1///29b1///a19v/9b//a/trW1trW1f+//W3trW1tr///W3///a1///a3tr" +
  "///a19vf+t///+v///b/9r/2Ptb9rf///tb/1v///a3//9vb9rf///X/9f///H/3t///Y///Y//tf+3/8X3" +
  "r+3//+2rf///a1/tf/H//a19vWtfW/tf+v3r/W+1f////j/+//U///t//X//+2//a1/7f//a1///H/+t///W" +
  "trX/b/v///H/rf+6/+2rf+//a1///H/+t///a/tW+N/rf+1v/r+9Wtf+//W+1trWvtf+//a3tr///8T///b/" +
  "tf////+v+1/9//rf///Y/rX29///W3///9/+tf//E//8T3rf//tb//9//+1f/3///8T///+1f2Ptd9//H+1" +
  "W/v///+X///2v+P9b/2Ptb///9//+v+X/2P///9///+3tr///2v9X///+tf///tf///tf///tf///tf///t" +
  "f///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///" +
  "tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf///tf//" +
  "//+2///W3trW3t/bW9vbe2t/vL+3r+uPx8fdx3v7/tbeWPv7xnt79feP+X/FtvX//r3eXm1vb37936+/Gdf" +
  "/j+jX/vj4eG9f+2KvrrcX/178W7X198fH//5ffPzX29ee/8e312vbx/G+8bHv/zH+X2zf+P9j+2Psf2T9j" +
  "58P/W3trW3t/bW9vbe2t/vL+3r+uPx8fdx3v7/tbeWPv7xnt79feP+X/FtvX//r3eXm1vb37936+/Gdf/j" +
  "o3///tf+3/FtrX/sf2///9f+3fv///1+/X/9f///H9t///H/+N/H9W71t6/tf7///+1tr/2v9R+2/7X/tf" +
  "2///9//b993/+2rfa//tf///H+2t//9v/2n/Y//r//X/+2///F/9//H9+//9//+t/rf9//rf///a/rf///" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "yFv19f/d//f/+uP5f+//a3trf3t7fb13tve0///b29rf9tb+uP/2e/X/x/Y//r8f4//f/vH/ePtf///Yxr" +
  "7+439c/x/DPx7Xffv2ceyx3Tfuj+0/7mvf1zXuq23/EY9te3/c/xG1/Y//j9jH//5jfL/+GOP//W/Xdf0/+" +
  "v9j28f1H+P+329fa9va3l7b2m/bP8Z+7Mc6/sc6/s/Y1v/v74/H2Df2se3rH8fx8WPtfz3GPh6PfXx/XMf" +
  "1/3GfbGx/6vHY1/bx2N7/9d++3/b/+O+b2zrY2x/v/GPrNuxH/H/sR//cTxjH6/t6/b//v9r///W9f9je+" +
  "3X77X9H9G2v/+I2n/EsW/H/rOObe3Hce0/sn/9j7H9P/K///1fj21s/9t/tI/1GP/3EY/t449v//U//p9" +
  "99/f/2/XtV0fYx8fH9t/e/39MY5rXx8v2bX+X+zb//Z/tS//1v//tf6//X/tf+7/V//1erT/H//7/s//fH" +
  "2/d1/W2/4e37+uPtz+/Fv1f++f7V3s72p/e/m+vtrd6a/F4fbzYvtX/Y//Rvq+1//+/1vvefr92/6i31v/" +
  "/tO2Pj/t/VGuM4+OPf/9Xe/Oet/t6O+7t++9e9vXW//7vWr/b7tX//t+v/+fHse3//qPefn/s/++v2ff+f" +
  "7V//6f+vta///Gv/+n/+v/+3+/F//P9/0ff/6v/1b7V/v6r///0P/r3f7Rvt//ov+tf6/Wv9e+/239Ee/H" +
  "vtT//r/f+H/X/s//s/9H/I9rx/+jf/pH//aPfa1/X//uP/N/++N/H/m//+Mcf6xjbX2//9vH/iPH/sX9Gj" +
  "OMYj3Esj2PsHf9H/GP9H/GPtY//b//H/l+Px5ff0xHvv/xTjW9n/9WNd//7+O67qPfYytv8bHMY6PY2xX2" +
  "2fsYz4ej2v9R4zj+/917GPc779n7P/tXvtfe2Xf/uMf//+/b/z//V//j2Nf/7//2MfH1+P//r9jXPv/9R/" +
  "xfzzG+r/j6x+Ptf/Hdv0/+v/+f/uPv/9f+3/FtrX/sf2///9f+3fv///1+/X/9f///H9t///H/+N/H9W71" +
  "t6/tf7///+1tr/2v9R+2/7X/tf2///9//b993/+2rfa//tf///H+2t//9v/2n/Y//r//X/+2///F/9//H9" +
  "+/9//+t/rf9//rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a" +
  "/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//" +
  "a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf///a/rf//"
;

// Tạo thư mục assets/icons nếu chưa có
const iconsDir = path.join(__dirname, 'assets', 'icons');
if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

// Lưu icon 192x192
const icon192Buffer = Buffer.from(icon192Base64, 'base64');
fs.writeFileSync(path.join(iconsDir, 'icon-192.png'), icon192Buffer);
console.log('Đã tạo assets/icons/icon-192.png');

// Lưu icon 512x512
const icon512Buffer = Buffer.from(icon512Base64, 'base64');
fs.writeFileSync(path.join(iconsDir, 'icon-512.png'), icon512Buffer);
console.log('Đã tạo assets/icons/icon-512.png');
