const { onCall } = require("firebase-functions/v2/https");
const { db, REGION, FieldValue, fail, requireUid, normalizeCode, roomRef, playerRef, secretRef } = require("./room-utils");

const heartbeatRoom=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode),ref=playerRef(code,uid);if(!(await ref.get()).exists)fail("NOT_ROOM_MEMBER");await ref.update({isConnected:true,lastSeenAt:FieldValue.serverTimestamp()});return{success:true};});

const leaveRoom=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode),rRef=roomRef(code),pRef=playerRef(code,uid);await db.runTransaction(async tx=>{const [r,p,players,boxes]=await Promise.all([tx.get(rRef),tx.get(pRef),tx.get(rRef.collection("players").where("hasLeft","==",false)),tx.get(rRef.collection("boxes"))]);if(!r.exists)fail("ROOM_NOT_FOUND");if(!p.exists)fail("NOT_ROOM_MEMBER");const room=r.data(),me=p.data(),now=FieldValue.serverTimestamp(),beforePlay=["lobby","writing","waiting-for-content","ready"].includes(room.phase);if(me.role==="host"&&beforePlay)tx.update(rRef,{status:"cancelled",phase:"result",completedAt:now,updatedAt:now});else if(beforePlay){boxes.docs.forEach(d=>tx.delete(d.ref));players.docs.forEach(d=>{tx.update(d.ref,{isReady:false,hasLockedContent:false});tx.delete(secretRef(code,d.id));});tx.update(pRef,{hasLeft:true,isConnected:false,isReady:false,lastSeenAt:now});tx.update(rRef,{status:"waiting",phase:"lobby",playerCount:1,currentTurnUid:null,winnerUid:null,updatedAt:now});}else tx.update(pRef,{hasLeft:true,isConnected:false,isReady:false,lastSeenAt:now});});return{success:true};});

const cancelRoom=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode);await db.runTransaction(async tx=>{const [r,p]=await Promise.all([tx.get(roomRef(code)),tx.get(playerRef(code,uid))]);if(!r.exists)fail("ROOM_NOT_FOUND");if(!p.exists||p.data().role!=="host")fail("NOT_HOST");tx.update(r.ref,{status:"cancelled",phase:"result",completedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});});return{success:true};});

const removeRoomPlayer=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode),targetUid=String(request.data?.playerUid||"");await db.runTransaction(async tx=>{const [r,me,target]=await Promise.all([tx.get(roomRef(code)),tx.get(playerRef(code,uid)),tx.get(playerRef(code,targetUid))]);if(!r.exists)fail("ROOM_NOT_FOUND");if(!me.exists||me.data().role!=="host")fail("NOT_HOST");if(r.data().phase!=="lobby")fail("ROOM_ALREADY_STARTED");if(!target.exists||target.data().role==="host")fail("PLAYER_NOT_FOUND");tx.update(target.ref,{hasLeft:true,wasRemoved:true,isConnected:false,isReady:false});tx.update(r.ref,{playerCount:FieldValue.increment(-1),updatedAt:FieldValue.serverTimestamp()});});return{success:true};});

const requestRematch=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode);await db.runTransaction(async tx=>{const [r,p]=await Promise.all([tx.get(roomRef(code)),tx.get(playerRef(code,uid))]);if(!r.exists)fail("ROOM_NOT_FOUND");if(r.data().phase!=="result")fail("INVALID_GAME_PHASE");if(!p.exists)fail("NOT_ROOM_MEMBER");tx.update(p.ref,{isReady:true});});return{success:true};});

const confirmRematch=onCall({region:REGION,cors:true,enforceAppCheck:false},async request=>{const uid=requireUid(request),code=normalizeCode(request.data?.roomCode),rRef=roomRef(code);await db.runTransaction(async tx=>{const [r,players,boxes]=await Promise.all([tx.get(rRef),tx.get(rRef.collection("players").where("hasLeft","==",false)),tx.get(rRef.collection("boxes"))]);if(!r.exists)fail("ROOM_NOT_FOUND");const me=players.docs.find(d=>d.id===uid);if(!me||me.data().role!=="host")fail("NOT_HOST");if(players.size!==2||!players.docs.every(d=>d.data().isReady))fail("PLAYERS_NOT_READY");boxes.docs.forEach(d=>tx.delete(d.ref));players.docs.forEach(d=>{tx.update(d.ref,{isReady:false,hasLockedContent:false});tx.delete(secretRef(code,d.id));});const now=FieldValue.serverTimestamp();tx.update(rRef,{status:"preparing",phase:"writing",currentTurnUid:null,winnerUid:null,revealedContent:null,turnNumber:1,roundNumber:FieldValue.increment(1),startedAt:null,completedAt:null,updatedAt:now});});return{success:true};});
module.exports={heartbeatRoom,leaveRoom,cancelRoom,removeRoomPlayer,requestRematch,confirmRematch};
